### ISSUE TITLE
Farbox-Next的主菜单项目

### ISSUE THREAD

**Issue by 18-1** [Sunnyyoung/Farbox-NexT#5]
谢谢博主提供克隆功能。我已经克隆了博主的next风格，请问为什么主菜单中只有「主页」和「归档」，没有「关于」「分类」「标签」等，希望放入主页的顶部菜单，请问应该如何设置？

**Comment by sunnyyoung** [comment]
@18-1 进入管理页面补充相关资料就可以了

**Comment by 18-1** [comment]
感谢回复！
请问是「NexT」页面吗？
我看到有基础信息-主题设置-主题特效-社交-微信二维码-打赏-友情链接，这几项，还不知道在哪里添加，再次请教，谢谢！

**Comment by sunnyyoung** [comment]
@18-1 
关于页面：直接在站点根目录下新建一个 about.md 文件即可。
设置分类：为 Dropbox 站点文件夹里面的子目录，一个子目录为一个分类。
设置标签：在 Mardown 文件中设置，如：

```yml
---
title: 关于 Markdown
date: 2016-07-27 21:51:12
Tags: About, Markdown
---

Markdown content.
```
